version: '3.8'

services:
  telegram-bot:
    build: .
    command: python agent.py --telegram
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped
    ports:
      - "8001:8001"
    networks:
      - tara-network

  whatsapp-webhook:
    build: .
    command: python agent.py --whatsapp --host 0.0.0.0 --port 8000
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - tara-network

networks:
  tara-network:
    driver: bridge
